on:
  push:
    paths:
    - 'rural_health_care_facilities/rural.json'
jobs: 
  build_database:
    runs-on: ubuntu-latest
    env:
        working-directory: ./rural_health_care_facilities/
    steps:
      - uses: actions/checkout@v2

      - name: Install python 3.8
        uses: actions/setup-python@v2
        with:
           python-version: 3.6
      - name: Install dependencies   
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: build database
        run: python build_database.py rural.db
