on:
  push:
    paths:
    - 'rural_health_care_facilities/rural.json'
  workflow_dispatch: 
     inputs:
       name:
         description: hi
         required: false
         default: 'oh hai'
jobs: 
  build_database:
    runs-on: ubuntu-latest
    env:
        working-directory: ./rural_health_care_facilities/
    steps:
      - uses: actions/checkout@v2

      - name: Install python 3.8
        uses: actions/setup-python@v2
        with:
           python-version: 3.6
      - name: Install dependencies   
        working-directory: ${{env.working-directory}}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: build database
        working-directory: ${{env.working-directory}}
        run: python build_database.py rural.db
      - name: Commit and push if it changed
        working-directory: ${{env.working-directory}}
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
