on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '3 3 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl curl 'https://services.arcgis.com/mMUesHYPkXjaFGfS/arcgis/rest/services/Rural_Health_Care_Facilities_in_Manitoba/FeatureServer/0/query?f=json&where=1%3D1&returnGeometry=true&spatialRel=esriSpatialRelIntersects&outFields=*&maxRecordCountFactor=4&outSR=102100&resultOffset=0&resultRecordCount=8000&cacheHint=true&quantizationParameters=%7B%22mode%22%3A%22view%22%2C%22originPosition%22%3A%22upperLeft%22%2C%22tolerance%22%3A1.058335450004233%2C%22extent%22%3A%7B%22xmin%22%3A-11340982.370110163%2C%22ymin%22%3A6275731.553112844%2C%22xmax%22%3A-10542884.62795418%2C%22ymax%22%3A7731051.972231458%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%2C%22latestWkid%22%3A3857%7D%7D%7D'   -H 'authority: services.arcgis.com'   -H 'user-agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36'   -H 'accept: */*'   -H 'origin: https://manitoba.maps.arcgis.com'   -H 'sec-fetch-site: same-site'   -H 'sec-fetch-mode: cors'   -H 'sec-fetch-dest: empty'   -H 'referer: https://manitoba.maps.arcgis.com/apps/webappviewer/index.html?id=0494058c6d8d437d8cd31c22b4253285'   -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8'   --compressed | jq . > rural_health_care_facilities/rural.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
